// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBy5qGbpIq4vC4G6ur6ExZYgHHW5eQ1ns',
    appId: '1:672692498710:web:e41477b7882bb1cf722037',
    messagingSenderId: '672692498710',
    projectId: 'mecommerceapp',
    authDomain: 'mecommerceapp.firebaseapp.com',
    storageBucket: 'mecommerceapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vI6p_rLjkT1tOMAlq1mqPYzMtZn3Mt8',
    appId: '1:672692498710:android:6d2607fbef4af6a8722037',
    messagingSenderId: '672692498710',
    projectId: 'mecommerceapp',
    storageBucket: 'mecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiP90R5bu-5zu6r5MavzdMBypROKwRagc',
    appId: '1:672692498710:ios:b932d052706f935e722037',
    messagingSenderId: '672692498710',
    projectId: 'mecommerceapp',
    storageBucket: 'mecommerceapp.appspot.com',
    iosClientId: '672692498710-rbe8qhpoqs82a2ukee46vvumpg1o39n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiP90R5bu-5zu6r5MavzdMBypROKwRagc',
    appId: '1:672692498710:ios:3d423b41bf6f1d49722037',
    messagingSenderId: '672692498710',
    projectId: 'mecommerceapp',
    storageBucket: 'mecommerceapp.appspot.com',
    iosClientId: '672692498710-6eqb0a5qvsc9ft3pb704174s4gf915eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp.RunnerTests',
  );
}
